!-----------------------!
 real(8) function gran()
!------------------------------------------------------------!
! Generates a random number from the normal distribution
! with mean 1 and standard deviation 1, using the Box-Muller
! transformation with uniform random numbers generated by an
! external function ran().
!------------------------------------------------------------!

 implicit none

 real(8) :: rr,v1,v2

 real(8), external :: ran

 do
    v1=2.d0*ran()-1.d0
    v2=2.d0*ran()-1.d0
    rr=v1**2+v2**2
    if (rr>0.d0.and.rr<1.d0) exit
 enddo
 gran=v1*sqrt(-2.d0*log(rr)/rr)

 end function gran
!------------------!
